/* ANTENEH RESEARCH HUB — reproducible analysis specification + browser-safe descriptive engine */
(()=>{
 const R=()=>JSON.parse(localStorage.getItem('arlab')||'{}'),W=x=>localStorage.setItem('arlab',JSON.stringify(x));
 const esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const mount=()=>document.getElementById('content');
 function csvParse(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
 function numeric(v){if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(String(v).trim());return Number.isFinite(n)?n:null}
 function describe(rows,headers){return headers.map((h,j)=>{const vals=rows.map(r=>r[j]??'');const nums=vals.map(numeric).filter(v=>v!==null),missing=vals.filter(v=>String(v).trim()==='').length;if(nums.length===vals.length-missing&&nums.length){const mean=nums.reduce((a,b)=>a+b,0)/nums.length;const sd=nums.length>1?Math.sqrt(nums.reduce((a,b)=>a+(b-mean)**2,0)/(nums.length-1)):0;return{name:h,type:'numeric',n:nums.length,missing,mean,sd,min:Math.min(...nums),max:Math.max(...nums)}}return{name:h,type:'categorical',n:vals.length-missing,missing,unique:new Set(vals.filter(v=>String(v).trim()!=='')).size}})}
 function rCode(s){const d=s.dataset||{};const a=s.analysisPlan||{};const file=(d.name||'data.csv').replace(/[^A-Za-z0-9_.-]/g,'_');return `# ANTENEH RESEARCH HUB — reproducible analysis specification\n# Generated: ${new Date().toISOString()}\n# This is a specification/template. Run it against the verified dataset; no results are invented.\n\ndata <- read.csv("${file}", stringsAsFactors = FALSE, check.names = FALSE)\n\n# Dataset: ${d.name||'not loaded'}\n# Rows: ${d.rows||'unknown'} | Columns: ${d.columns||'unknown'}\n\n# Primary outcome: ${a.outcome||'NOT SPECIFIED'}\n# Primary exposure/predictor: ${a.exposure||'NOT SPECIFIED'}\n# Descriptive analysis: ${a.descriptive||'NOT SPECIFIED'}\n# Primary model/test: ${a.model||'NOT SPECIFIED'}\n# Missing-data strategy: ${a.missing||'NOT SPECIFIED'}\n\n# Basic audit\nstr(data)\nsummary(data)\ncolSums(is.na(data))\n\n# Add only analyses approved in the methodology and statistical analysis plan.\n# Record effect estimates, 95% confidence intervals and p-values where appropriate.\n# Preserve the exact code and dataset version used for every reported result.\n`}
 function render(){const el=mount();if(!el)return;const s=R(),d=s.dataset,a=s.analysisPlan;let html='<div class="card"><h4>Statistical analysis & traceability</h4><p>R is the primary execution target. R is free/open-source statistical software with built-in statistical and graphics capabilities. The Hub generates reproducible specifications but never fabricates statistical results.</p>';if(!d){html+='<div class="notice">Load a verified CSV dataset first.</div></div>';el.insertAdjacentHTML('afterbegin',html);return}const stats=d.summary||[];html+=`<div class="notice"><b>${esc(d.name)}</b><br>${d.rows} rows · ${d.columns} columns</div>`;if(stats.length)html+='<h5>Descriptive audit</h5>'+stats.map(x=>x.type==='numeric'?`<div class="paper"><b>${esc(x.name)}</b> · numeric · n=${x.n} · missing=${x.missing}<br>Mean ${x.mean.toFixed(3)} · SD ${x.sd.toFixed(3)} · range ${x.min}–${x.max}</div>`:`<div class="paper"><b>${esc(x.name)}</b> · categorical · n=${x.n} · missing=${x.missing} · unique=${x.unique}</div>`).join('');html+=`<h5>Approved analysis plan</h5><div class="paper">Outcome: ${esc(a?.outcome||'not specified')}<br>Exposure: ${esc(a?.exposure||'not specified')}<br>Model/test: ${esc(a?.model||'not specified')}<br>Status: ${a?.approved?'APPROVED':'DRAFT'}</div><button class="btn primary" id="rcopy">Generate R analysis specification</button><textarea id="rcode" style="min-height:260px;margin-top:10px" readonly>${esc(rCode(s))}</textarea></div>`;el.insertAdjacentHTML('afterbegin',html);document.getElementById('rcopy').onclick=()=>{navigator.clipboard?.writeText(rCode(R()));alert('R analysis specification copied.')}}
 window.AnalysisEngine={ingestText(text,name){const rows=csvParse(text);if(rows.length<2)throw Error('CSV needs a header and at least one data row.');const headers=rows[0].map(x=>String(x).trim()),data=rows.slice(1),s=R();s.dataset={...(s.dataset||{}),name,rows:data.length,columns:headers.length,headers,dataDictionary:describe(data,headers),summary:describe(data,headers),importedAt:new Date().toISOString()};W(s);render();return s.dataset},render};
 setTimeout(render,250);
})();
