/* ANTENEH RESEARCH HUB — traceable conclusion & recommendations */
(()=>{
 const read=()=>JSON.parse(localStorage.getItem('arlab')||'{}');
 const write=s=>localStorage.setItem('arlab',JSON.stringify(s));
 const esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const add=html=>{const c=document.getElementById('content');if(c)c.insertAdjacentHTML('afterbegin',html)};
 const fingerprint=s=>JSON.stringify({title:s.title||'',dataset:s.dataset?.provenance||null,results:s.resultsSnapshot||null,discussion:s.s16||'',literature:s.literatureSynthesis||null});
 const audit=(label,s)=>{s.provenanceLog=Array.isArray(s.provenanceLog)?s.provenanceLog:[];s.provenanceLog.push({time:new Date().toISOString(),label,stage:Number(s.current||17),title:s.title||'',dataset:s.dataset?.name||'',resultsTrace:!!s.resultsSnapshot,literatureApproved:!!s.literatureSynthesisApproved,discussion:!!s.s16});s.provenanceLog=s.provenanceLog.slice(-100)};
 const draft=s=>`CONCLUSION\n\nPrincipal conclusion\n${s.s16?'This conclusion is derived from the verified findings and the approved interpretation recorded in the Discussion stage. The researcher must replace this guidance with a study-specific conclusion supported by the evidence.':'No approved Discussion is available yet. Complete and approve the Discussion before finalizing the conclusion.'}\n\nRecommendations\n1. State only recommendations directly supported by the verified findings.\n2. Separate practical implications from policy recommendations and identify the population/context to which they apply.\n3. Do not introduce new statistics, new literature claims, or causal assertions that were not established earlier.\n4. Where evidence is uncertain or limited, recommend targeted further research rather than presenting speculation as established evidence.\n\nScope and uncertainty\nState clearly what the study can and cannot support, including design, sampling, measurement, missing-data and generalisability limitations.\n\nResearch priorities\nIdentify unanswered questions that follow from the verified evidence and limitations.`;
 function render(i){if(i!==17)return;const s=read();add(`<div class="card"><h4>Conclusion & recommendations — evidence-locked workspace</h4><p>This stage can summarize verified findings and approved interpretation, but it must not create new evidence. Reporting guidance should match the actual study design; EQUATOR maintains study-specific guidelines for major designs. </p><textarea id="crText" style="min-height:360px">${esc(s.s17||draft(s))}</textarea><div class="actions"><button class="btn primary" id="crSave">Save conclusion</button><button class="btn" id="crApprove">Approve conclusion</button></div><div class="notice" style="margin-top:12px">Before approval: verify that every recommendation is supported by the results/discussion, the target population is explicit, uncertainty is acknowledged, and no new statistical result has been introduced.</div></div>`);crSave.onclick=()=>{const x=read();x.s17=crText.value;x.conclusionAt=new Date().toISOString();x.conclusionFingerprint=fingerprint(x);audit('Saved conclusion draft',x);write(x);alert('Conclusion draft saved and audited.')};crApprove.onclick=()=>{const x=read();if(!x.s17?.trim()){alert('Write the conclusion before approval.');return}if(!x.resultsSnapshot&&!x.inferentialResults?.length){alert('A verified results record is required before approval.');return}if(!x.s16?.trim()){alert('An approved Discussion should be completed before approving the conclusion.');return}x.conclusionApproved=true;x.conclusionApprovedAt=new Date().toISOString();x.conclusionFingerprint=fingerprint(x);audit('Approved conclusion and recommendations',x);write(x);alert('Conclusion and recommendations approved and provenance-recorded.')}}
 window.ConclusionRuntime={render};
})();
