/* ANTENEH RESEARCH HUB — guarded inferential statistics layer */
(()=>{
 const R=()=>JSON.parse(localStorage.getItem('arlab')||'{}'),W=x=>localStorage.setItem('arlab',JSON.stringify(x));
 const E=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const avg=a=>a.reduce((x,y)=>x+y,0)/a.length;
 const variance=a=>a.length>1?a.reduce((x,y)=>x+(y-avg(a))**2,0)/(a.length-1):0;
 function erf(x){const s=x<0?-1:1,a=Math.abs(x),t=1/(1+0.3275911*a),p=1.061405429-1.453152027*t+1.421413741*t*t-0.284496736*t*t*t+0.254829592*t*t*t*t;return s*(1-p*Math.exp(-a*a))}
 function normalP(z){return 2*(1-(0.5*(1+erf(Math.abs(z)/Math.sqrt(2)))))}
 function tTestOne(a,mu){const n=a.length;if(n<2)return null;const m=avg(a),se=Math.sqrt(variance(a)/n),t=(m-mu)/se;return{n,mean:m,sd:Math.sqrt(variance(a)),t,pApprox:normalP(t),se,ciLow:m-1.96*se,ciHigh:m+1.96*se}}
 function render(){const c=document.getElementById('content');if(!c)return;const s=R(),d=s.dataset,a=s.analysisPlan;if(!d?.headers||!d?.data){c.insertAdjacentHTML('afterbegin','<div class="card"><h4>Inferential analysis</h4><p>Import a verified dataset first.</p></div>');return}if(!a?.approved){c.insertAdjacentHTML('afterbegin','<div class="card"><h4>Inferential analysis gate</h4><div class="notice">Approve the analysis plan before running inferential statistics.</div></div>');return}const nums=(d.dataDictionary||[]).filter(x=>x.numeric).map(x=>x.name);c.insertAdjacentHTML('afterbegin','<div class="card"><h4>Inferential analysis</h4><p>Guarded execution: this layer runs only the explicitly selected approved test and records its provenance.</p><label>Numeric outcome<select id="iv">'+nums.map(x=>'<option>'+E(x)+'</option>').join('')+'</select></label><label>Null/reference mean<input id="imu" type="number" value="0"></label><button class="btn primary" id="irun">Run one-sample test</button><div id="io" style="margin-top:12px"></div></div>');document.getElementById('irun').onclick=()=>{const s=R(),d=s.dataset,j=d.headers.indexOf(document.getElementById('iv').value),v=d.data.map(r=>Number(r[j])).filter(Number.isFinite),mu=Number(document.getElementById('imu').value);const out=tTestOne(v,mu);if(!out)return;const result={test:'one-sample t-test',variable:d.headers[j],nullMean:mu,...out,dataset:d.name,analysisPlanVersion:s.analysisPlan.updatedAt||null,generatedAt:new Date().toISOString(),method:'browser calculation; p-value is normal approximation only'};s.inferentialResults=s.inferentialResults||[];s.inferentialResults.push(result);W(s);document.getElementById('io').innerHTML='<h5>Result</h5><table><tr><th>Outcome</th><th>N</th><th>Mean</th><th>SD</th><th>t</th><th>p*</th><th>95% CI</th></tr><tr><td>'+E(result.variable)+'</td><td>'+out.n+'</td><td>'+out.mean.toFixed(3)+'</td><td>'+out.sd.toFixed(3)+'</td><td>'+out.t.toFixed(3)+'</td><td>'+out.pApprox.toFixed(4)+'</td><td>'+out.ciLow.toFixed(3)+' to '+out.ciHigh.toFixed(3)+'</td></tr></table><p><small>*Normal-approximation p-value; for publication, verify with the R execution engine and the approved analysis specification.</small></p><div class="notice">Trace: '+E(d.name)+' → '+E(result.variable)+' → approved plan → one-sample test → result snapshot.</div>'};}
 window.InferentialEngine={render};setTimeout(render,500);
})();