/* ANTENEH RESEARCH HUB — traceable manuscript assembly */
(()=>{
 const read=()=>JSON.parse(localStorage.getItem('arlab')||'{}');
 const write=s=>localStorage.setItem('arlab',JSON.stringify(s));
 const esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const add=html=>{const c=document.getElementById('content');if(c)c.insertAdjacentHTML('afterbegin',html)};
 const audit=(label,s)=>{const x={time:new Date().toISOString(),label,stage:Number(s.current||0),title:s.title||'',evidence:Array.isArray(s.evidence)?s.evidence.length:0,methodologyApproved:!!s.methodology?.approved,analysisPlanApproved:!!s.analysisPlan?.approved,dataset:s.dataset?{name:s.dataset.name,rows:s.dataset.rows,columns:s.dataset.columns}:null,rVerified:!!s.rExecution,resultsSaved:!!s.resultsSnapshot};s.provenanceLog=Array.isArray(s.provenanceLog)?s.provenanceLog:[];s.provenanceLog.push(x);s.provenanceLog=s.provenanceLog.slice(-100)};
 const numericSummary=d=>(d?.dataDictionary||[]).filter(x=>x.numeric).map(x=>{const j=d.headers.indexOf(x.name),v=d.data.map(r=>Number(r[j])).filter(Number.isFinite);if(!v.length)return null;const m=v.reduce((a,b)=>a+b,0)/v.length;const sd=v.length>1?Math.sqrt(v.reduce((a,b)=>a+(b-m)**2,0)/(v.length-1)):0;return{name:x.name,n:v.length,mean:m,sd,min:Math.min(...v),max:Math.max(...v)}}).filter(Boolean);
 function evidenceList(s){return (s.evidence||[]).slice(0,30).map((p,i)=>`${i+1}. ${p.title||'Untitled'}${p.year?' ('+p.year+')':''}${p.journal?' — '+p.journal:''}${p.url?' — '+p.url:''}`).join('\n');}
 function resultsDraft(s){const d=s.dataset,stats=numericSummary(d),inf=s.inferentialResults||[];let out='RESULTS\n\n';out+=`Dataset: ${d?.name||'Not loaded'}\nObservations: ${d?.rows??'Unknown'}\nVariables: ${d?.columns??'Unknown'}\n\nDescriptive statistics\n`;out+=stats.length?stats.map(x=>`• ${x.name}: n=${x.n}, mean=${x.mean.toFixed(3)}, SD=${x.sd.toFixed(3)}, range=${x.min}–${x.max}`).join('\n'):'No numeric variables available.';if(inf.length){out+='\n\nInferential results (executed and provenance-recorded)\n'+inf.map(x=>`• ${x.test}: ${x.variable}; n=${x.n}; estimate/mean=${Number(x.mean).toFixed(3)}; test statistic=${Number(x.t??NaN).toFixed(3)}; p=${Number(x.pApprox??NaN).toFixed(4)}; 95% CI=${Number(x.ciLow??NaN).toFixed(3)} to ${Number(x.ciHigh??NaN).toFixed(3)}. Browser p-values must be verified with R before publication.`).join('\n')}return out;}
 function discussionDraft(s){const title=s.title||'This study';return `DISCUSSION\n\n${title} — interpretation framework\n\nThe discussion should interpret only the verified results recorded in the Results stage. Begin by stating the principal finding(s), then compare them with the screened literature. Explain plausible mechanisms or interpretations only when supported by the study design and evidence. Distinguish association from causation and avoid claims that exceed the sampling frame or measurement quality.\n\nPrincipal finding(s)\n${s.s14||resultsDraft(s)}\n\nComparison with prior evidence\nUse the verified evidence map below. Do not infer agreement or disagreement until individual sources have been screened and relevant findings extracted.\n${evidenceList(s)||'No verified literature records saved.'}\n\nLimitations\nState design limitations, sampling limitations, measurement limitations, missing data, potential bias and generalisability explicitly.\n\nImplications\nRecommendations must follow from the verified results, study design and evidence base.`;}
 function conclusionDraft(s){return `CONCLUSION\n\nBased on the verified dataset and approved analysis plan, summarize the principal findings without introducing new statistics or unsupported causal claims.\n\nRecommendations\n1. Recommendations directly supported by the findings.\n2. Practical or policy implications supported by the evidence.\n3. Priorities for future research where uncertainty remains.\n\nNo new results should be introduced in this section.`;}
 function qc(s){const checks=[['Research title recorded',!!s.title],['Evidence records available',Array.isArray(s.evidence)&&s.evidence.length>0],['Methodology reviewed',!!s.methodology],['Methodology approved',!!s.methodology?.approved],['Dataset loaded',!!s.dataset?.data?.length],['Analysis plan approved',!!s.analysisPlan?.approved],['Results trace exists',!!s.resultsSnapshot||!!s.inferentialResults],['No fabricated-result rule enabled',true]];return checks;}
 function manuscript(s){return `TITLE\n${s.title||'[Research title]'}\n\nABSTRACT\nBackground: ${s.s1||'[Approved problem statement]'}\nObjective: ${s.s3||'[Approved objectives]'}\nMethods: ${s.s7||'[Approved methodology]'}\nResults: ${s.s14||resultsDraft(s)}\nConclusion: ${s.s17||conclusionDraft(s)}\n\n1. INTRODUCTION\nProblem statement\n${s.s1||'[Approved content]'}\n\nKnowledge gap\n${s.s2||'[Approved content]'}\n\nObjectives\n${s.s3||'[Approved content]'}\n\nResearch questions\n${s.s4||'[Approved content]'}\n\n2. METHODS\n${s.s7||'[Approved methodology]'}\n\nSampling\n${s.s8||'[Approved sampling plan]'}\n\nInstrument and data collection\n${s.s9||'[Approved instrument/data-collection plan]'}\n\nData quality\n${s.s11||'[Approved data-quality plan]'}\n\nStatistical analysis\n${s.s12||'[Approved statistical analysis plan]'}\n\n3. RESULTS\n${s.s14||resultsDraft(s)}\n\n4. DISCUSSION\n${s.s16||discussionDraft(s)}\n\n5. CONCLUSION AND RECOMMENDATIONS\n${s.s17||conclusionDraft(s)}\n\nREFERENCES\n${evidenceList(s)||'[Verified references will appear here after source screening and metadata validation.]'}\n\nRESEARCH AUDIT NOTE\nThis manuscript draft is assembled from the current research workspace. Statistical values must remain traceable to the dataset and executed analysis. Citations must remain traceable to verified source metadata. Publication acceptance is not guaranteed.`;}
 function exportText(text,name){const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 function render(i){const s=read();if(i===14){add(`<div class="card"><h4>Verified results narrative</h4><p>The draft below is assembled only from stored dataset calculations and executed analysis records. Edit it only after reviewing the underlying output.</p><textarea id="meResults" style="min-height:320px">${esc(s.s14||resultsDraft(s))}</textarea><button class="btn primary" id="meSaveResults">Save results narrative</button></div>`);meSaveResults.onclick=()=>{const x=read();x.s14=meResults.value;x.resultsNarrativeAt=new Date().toISOString();audit('Saved results narrative',x);write(x);alert('Results narrative saved and audited.')}}
 if(i===16){add(`<div class="card"><h4>Discussion evidence framework</h4><p>Separates verified findings from interpretation. Literature is presented as a source list until findings are screened.</p><textarea id="meDisc" style="min-height:360px">${esc(s.s16||discussionDraft(s))}</textarea><button class="btn primary" id="meSaveDisc">Save discussion</button></div>`);meSaveDisc.onclick=()=>{const x=read();x.s16=meDisc.value;x.discussionAt=new Date().toISOString();audit('Saved discussion',x);write(x);alert('Discussion saved and audited.')}}
 if(i===17){add(`<div class="card"><h4>Conclusion & recommendations</h4><textarea id="meConc" style="min-height:300px">${esc(s.s17||conclusionDraft(s))}</textarea><button class="btn primary" id="meSaveConc">Save conclusion</button></div>`);meSaveConc.onclick=()=>{const x=read();x.s17=meConc.value;x.conclusionAt=new Date().toISOString();audit('Saved conclusion',x);write(x);alert('Conclusion saved and audited.')}}
 if(i===18){add(`<div class="card"><h4>Reference audit</h4><p>Only retrieved scholarly records are listed. Screen each source before using it as evidence in the manuscript.</p><div class="notice">${evidenceList(s)||'No evidence records available.'}</div></div>`)}
 if(i===19){const c=qc(s);add(`<div class="card"><h4>Academic quality-control gate</h4><p>Green checks indicate stored evidence exists; they do not replace expert review.</p>${c.map(x=>`<div class="paper"><b>${x[1]?'✓':'⚠'} ${esc(x[0])}</b></div>`).join('')}<button class="btn primary" id="meQC">Save QC snapshot</button></div>`);meQC.onclick=()=>{const x=read();x.qualityControl={checks:c.map(y=>({item:y[0],pass:y[1]})),generatedAt:new Date().toISOString()};audit('Saved quality-control snapshot',x);write(x);alert('Quality-control snapshot saved and audited.')}}
 if(i===20){add(`<div class="card"><h4>Publication manuscript assembler</h4><p>Assembles approved lifecycle sections plus traceable results. It does not claim publication acceptance.</p><textarea id="meMan" style="min-height:520px">${esc(s.s20||manuscript(s))}</textarea><div class="actions"><button class="btn primary" id="meSaveMan">Save manuscript</button><button class="btn" id="meTxt">Export TXT</button></div></div>`);meSaveMan.onclick=()=>{const x=read();x.s20=meMan.value;x.manuscriptAt=new Date().toISOString();audit('Saved manuscript draft',x);write(x);alert('Manuscript draft saved and audited.')};meTxt.onclick=()=>exportText(meMan.value,'anteneh-research-hub-manuscript.txt')}
 if(i===21){add(`<div class="card"><h4>Export & research audit package</h4><p>Export the complete research workspace as JSON or the assembled manuscript as plain text. Use regular backups before important data collection.</p><div class="actions"><button class="btn primary" id="meJSON">Export research JSON</button><button class="btn" id="meTXT">Export manuscript TXT</button></div></div>`);meJSON.onclick=()=>exportText(JSON.stringify(read(),null,2),'anteneh-research-hub-project.json');meTXT.onclick=()=>exportText(read().s20||manuscript(read()),'anteneh-research-hub-manuscript.txt')}
 }
 window.ManuscriptEngine={render};
})();