(()=>{
  const R=()=>JSON.parse(localStorage.getItem('arlab')||'{}');
  const W=x=>localStorage.setItem('arlab',JSON.stringify(x));
  const esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const snapshot=s=>({time:new Date().toISOString(),stage:Number(s.current||0),title:s.title||'',evidence:s.evidence?.length||0,methodologyApproved:!!s.methodology?.approved,analysisPlanApproved:!!s.analysisPlan?.approved,dataset:s.dataset?{name:s.dataset.name,rows:s.dataset.rows,columns:s.dataset.columns}:null,rVerified:!!s.rExecution,resultsSaved:!!s.resultsSnapshot});
  function record(label){const s=R(),entry={label,...snapshot(s)};s.provenanceLog=Array.isArray(s.provenanceLog)?s.provenanceLog:[];s.provenanceLog.push(entry);s.provenanceLog=s.provenanceLog.slice(-100);W(s);return entry}
  function render(){const c=document.getElementById('content');if(!c||document.getElementById('provenance-card'))return;const s=R(),log=s.provenanceLog||[];c.insertAdjacentHTML('afterbegin','<div class="card" id="provenance-card"><h4>Research provenance & audit trail</h4><p>Records major research-state snapshots so decisions and outputs can be traced over time.</p><div class="notice"><b>Current state:</b> stage '+(Number(s.current||0)+1)+' · '+esc(s.title||'Untitled')+' · '+(s.evidence?.length||0)+' evidence records</div><div class="actions"><button class="btn primary" id="provCapture">Capture research checkpoint</button><button class="btn" id="provExport">Export audit trail</button></div><div id="provLog" style="margin-top:10px">'+(log.length?log.slice().reverse().slice(0,8).map(x=>'<div class="paper"><b>'+esc(x.label)+'</b><br><small>'+esc(x.time)+' · stage '+(x.stage+1)+' · evidence '+x.evidence+' · methodology '+(x.methodologyApproved?'approved':'pending')+' · analysis '+(x.analysisPlanApproved?'approved':'pending')+' · R '+(x.rVerified?'verified':'pending')+'</small></div>').join(''):'<div class="paper">No checkpoints captured yet.</div>')+'</div></div>');document.getElementById('provCapture').onclick=()=>{record('Manual research checkpoint');render();alert('Research checkpoint captured.')};document.getElementById('provExport').onclick=()=>{const blob=new Blob([JSON.stringify(R().provenanceLog||[],null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='anteneh-research-provenance.json';a.click();URL.revokeObjectURL(a.href)}}
  window.ProvenanceEngine={record,render,snapshot};
  setTimeout(render,1200);
})();