/* ANTENEH RESEARCH HUB — questionnaire builder */
(()=>{
 const L=[['am','አማርኛ'],['om','Afaan Oromoo'],['sid','Sidaamu Afoo']];
 const read=()=>JSON.parse(localStorage.getItem('arlab')||'{}');
 const write=s=>localStorage.setItem('arlab',JSON.stringify(s));
 const esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const add=h=>{const c=document.getElementById('content');if(c&&!document.getElementById('questionnaire-builder'))c.insertAdjacentHTML('afterbegin',h)};
 function render(stage){if(stage!==9)return;const s=read();add(`<div class="card" id="questionnaire-builder"><h4>📋 Questionnaire Builder</h4><p>Create analysis-safe questions while preparing respondent-facing translations.</p><div class="field"><label>QUESTION NAME (stable analysis ID)</label><input id="qbName" placeholder="e.g. age"></div><div class="field"><label>TYPE</label><select id="qbType"><option value="text">Text</option><option value="integer">Integer</option><option value="decimal">Decimal</option><option value="select_one">Select one</option><option value="select_multiple">Select multiple</option><option value="date">Date</option><option value="geopoint">GPS</option></select></div><div class="field"><label>AMHARIC LABEL</label><input id="qbAm" placeholder="የጥያቄው ጽሑፍ"></div><div class="field"><label>AFAAN OROMOO LABEL</label><input id="qbOm" placeholder="Gaaffii Afaan Oromoo"></div><div class="field"><label>SIDAAMU AFOO LABEL</label><input id="qbSid" placeholder="Sidaamu Afoo gaaffii"></div><div class="field"><label>CHOICES (one per line; for select questions)</label><textarea id="qbChoices" placeholder="yes\nno"></textarea></div><label style="display:block;margin:8px 0"><input id="qbRequired" type="checkbox"> Required</label><button class="btn primary" id="qbSave">Add question</button><div id="qbList" class="paper" style="margin-top:12px"></div></div>`);const list=()=>{const x=read(),q=Array.isArray(x.questionnaire)?x.questionnaire:[];document.getElementById('qbList').innerHTML=q.length?'<b>Saved questions</b><br>'+q.map((v,i)=>`${i+1}. <b>${esc(v.name)}</b> — ${esc(v.type)} — ${v.required?'required':'optional'}<br><small>${esc(v.labels?.am||'')} | ${esc(v.labels?.om||'')} | ${esc(v.labels?.sid||'')}</small>`).join('<hr>'):'No questions saved yet.'};document.getElementById('qbSave').onclick=()=>{const name=document.getElementById('qbName').value.trim();if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)){alert('Use a stable Latin analysis name, e.g. age_respondent.');return}const x=read();x.questionnaire=Array.isArray(x.questionnaire)?x.questionnaire:[];if(x.questionnaire.some(q=>q.name===name)){alert('That question name already exists.');return}x.questionnaire.push({name,type:document.getElementById('qbType').value,labels:{am:document.getElementById('qbAm').value,om:document.getElementById('qbOm').value,sid:document.getElementById('qbSid').value},choices:document.getElementById('qbChoices').value.split(/\n/).map(v=>v.trim()).filter(Boolean),required:document.getElementById('qbRequired').checked,createdAt:new Date().toISOString()});write(x);list();['qbName','qbAm','qbOm','qbSid','qbChoices'].forEach(id=>document.getElementById(id).value='');document.getElementById('qbRequired').checked=false};list()}
 window.QuestionnaireBuilder={render};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>render(Number(read().current||0)));else render(Number(read().current||0));setInterval(()=>render(Number(read().current||0)),1500);
})();
